### ISSUE TITLE
Stuff on SD cards

### ISSUE THREAD

**Issue by gbaman** [raspberrypilearning/teachers-classroom-guide#4]
Perhaps a section on SD cards in here other than just pointing them to where they can buy a preflashed SD card with NOOBS.
Have to keep in mind that all the schools that received Google Pi kids which is a massive majority of teachers that will be reading this have, these are 4gb cards.
NOOBS does not currently (and hasn't for 4-5 months) fitted onto a 4gb card. We can't simply ignore all the people out there with 4gb cards (seeing as a majority are complete beginners at Raspberry Pi educators).

Perhaps a section with 2 parts.
1. What to do if you have a 8gb card (or greater) linking to the NOOBSs documentation
2. What to do if you have a 4gb card linking to http://www.raspberrypi.org/documentation/installation/installing-images/README.md

On top of this, perhaps a simple guide on cloning SD cards using Win32DiskImager? I know it is far from the optimum way to do it, but it certainly is simple. (To clarify I am talking about flashing 1 card, making your needed changes, then reading it back into win32diskimager ready to write to the next card)

**Comment by lurch** [comment]
Since 12th September 2014 (coincidentally just after you filed this issue!), NOOBS has only included Raspbian http://www.raspberrypi.org/documentation/installation/noobs.md and therefore fits (just) on 4GB cards again :-)

There's a bit about using Win32DiskImager to clone a whole load of cards at https://github.com/raspberrypilearning/networking-lessons/blob/master/lesson-1/teacher-instructions.md but I agree that this is something that probably warrants a standalone guide (that the resources could all link to), rather than having each resource copy'n'paste the same info https://github.com/raspberrypilearning/networking-lessons/issues/15

**Comment by gbaman** [comment]
Haha, had forgotten about this open issue.
The instructions in network lessons for cloning SD cards are a little vague, "On Windows use Win disk 32 imager to make a copy of an SD card. On Mac OS X you can use the dd command or a dd-gui."
If I was a teacher and only just opened up Win32 Disk Imager for the first time, I wouldn't have a clue how to make a copy of the SD card, and as for Mac/Linux...
Something like the resource in this issue might be more suitable https://github.com/raspberrypilearning/teachers-classroom-guide/issues/6.
